name: uhi-twin-cities
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - flake8-isort==2.7.0
    - invest-ucm-calibration==0.4.1
  - setuptools
  - wheel
  - click
  - sphinx
  - coverage
  - flake8
  - awscli  
  - python-dotenv>=0.5.1
  - python=3
  - ipykernel
  - gdal<3.0
  - matplotlib
  - nbconvert
  - papermill
  - rtree
  - shapely<1.7.0
